### ISSUE TITLE
System.DllNotFoundException: Gtk: libgtk-3-0.dll

### ISSUE THREAD

**Issue by jiriks74** [GtkSharp/GtkSharp#337]
Hi,
I'm using `GtkSharp` library to develop on linux and everything works as far as I'm running it on linux. But when I try to make a windows build things break.

When I do `dotnet build --runtime win-x64` I get everything I need (even `libgtk-3-0.dll`), but when I try to run it on windows, I get an error (title). 

When I try `dotnet publish --runtime win-x64` the library isn't even present in the `publish` directory and the error is the same. 

I need to publish the app for windows and I am not able to install GTK on the target machine and it should be ok as the library should be included in the runtime.

What am I doing wrong?

**Comment by cameronwhite** [comment]
FWIW, I solved this by pulling in the GTK libraries when building the installer (skipping stuff like the gtkmm libraries which aren't needed)
https://github.com/PintaProject/Pinta/blob/master/installer/windows/installer.iss#L32

**Comment by jiriks74** [comment]
> FWIW, I solved this by pulling in the GTK libraries when building the installer (skipping stuff like the gtkmm libraries which aren't needed) https://github.com/PintaProject/Pinta/blob/master/installer/windows/installer.iss#L32

Well I'm not making an installer... I'm just making simple applications so far. I'll be using c# in a competition where the "judges" use windows and I won't have time to make an installer (it's about 4 hours)

**Comment by cameronwhite** [comment]
The relevant part of it is doing a folder copy from `%LOCALAPPDATA%\Gtk\3.24.24` (where GtkSharp's downloaded the GTK libraries to) to your publish folder.
Anyways, I was just trying to help by offering a possible idea ..

**Comment by jiriks74** [comment]
Thanks, I'll take a look at that, but I'm developing it on Linux and publishing for Windows. I'll take a look where the files are located in Linux and go from there

Also, here's the whole error I get:
```csharp
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at simpleText.simpleText.Main(String[] args) in /config/workspace/simpleText/Program.cs:line 9
```

**Comment by jiriks74** [comment]
@cameronwhite 

Well in `~/.nuget/packages/gtksharp/3.24.24.34/` directory I get only `build  gtksharp.3.24.24.34.nupkg  gtksharp.3.24.24.34.nupkg.sha512  gtksharp.nuspec  lib`. In `build` there's only `GtkSharp.targets` and in `lib` there's only `/netstandard2.0/GtkSharp.dll`.

**Comment by cameronwhite** [comment]
On Linux I think it just uses the GTK libraries that are installed on your system.

**Comment by jiriks74** [comment]
> On Linux I think it just uses the GTK libraries that are installed on your system.


Solved by copying libraries from here: `~/.nuget/packages/gtksharp.dependencies/1.1.1/contentFiles/cs/netstandard2.0/bin/` (`GtkSharp.Dependencies` package`)

The Window spawns, but I get this now:
```
(simpleText:6800): Gtk-WARNING **: 23:14:19.150: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(simpleText:6800): Gtk-WARNING **: 23:14:19.158: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

**Comment by jiriks74** [comment]
Looks like I got that fixed. I have the build with the needed libraries in `bin` directory, but I need it in the `publish` (`../` from the `build` directory).

@cameronwhite

**Comment by koaie** [comment]
@jiriks74 Could you explain how you got the issue fixed?
copying `~/.nuget/packages/gtksharp.dependencies/1.1.1/contentFiles/cs/netstandard2.0/bin/` to the publish folder or the bin subfolder did not solve the issue.

thanks in advance.

**Comment by jiriks74** [comment]
> @jiriks74 Could you explain how you got the issue fixed? copying `~/.nuget/packages/gtksharp.dependencies/1.1.1/contentFiles/cs/netstandard2.0/bin/` to the publish folder or the bin subfolder did not solve the issue.
> 
> thanks in advance.

I used some other NuGet package. It was [`GtkSharp.Dependencies`](https://www.nuget.org/packages/GtkSharp.Dependencies) I think? It added the needed libraries into a `bin/` folder, but the exe wouldn't look into the folder, so you had to move the libraries manually for the app to work.

**Comment by rbwork2024** [comment]
Writing my solution here in case anyone runs into this papercut :)

Note: If your application is cross-platform, or you're building on a non-windows platform for windows, you'll wanna modify this. All it's doing is grabbing the libraries from where GTKSharp installs them, and plopping them into the output directory.

What an annoying bug 😓 

```
<!-- Bundle GTK in the final output -->
<Content Include="C:\Users\$(UserName)\AppData\Local\Gtk\3.24.24\**\*">
	<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```
